/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as MotDePasseOublieRouteImport } from './routes/mot-de-passe-oublie'
import { Route as ReinitialiserMotDePasseRouteImport } from './routes/reinitialiser-mot-de-passe'
import { Route as AuthenticatedBibliothequeRouteImport } from './routes/_authenticated/bibliotheque'
import { Route as AuthenticatedCreditsRouteImport } from './routes/_authenticated/credits'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedParametresRouteImport } from './routes/_authenticated/parametres'
import { Route as AuthenticatedTarifsRouteImport } from './routes/_authenticated/tarifs'
import { Route as AuthenticatedTextesRouteImport } from './routes/_authenticated/textes'
import { Route as AuthenticatedVeilleRouteImport } from './routes/_authenticated/veille'
import { Route as AuthenticatedVideoRouteImport } from './routes/_authenticated/video'
import { Route as AuthenticatedVisuelsRouteImport } from './routes/_authenticated/visuels'
import { Route as AuthenticatedAdminCreditsRouteImport } from './routes/_authenticated/admin.credits'
import { Route as AuthenticatedEbooksIndexRouteImport } from './routes/_authenticated/ebooks.index'
import { Route as AuthenticatedEbooksIdRouteImport } from './routes/_authenticated/ebooks.$id'
import { Route as AuthenticatedEbooksNouveauRouteImport } from './routes/_authenticated/ebooks.nouveau'
import { Route as ApiPublicWebhooksProviderRouteImport } from './routes/api/public/webhooks/$provider'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const MotDePasseOublieRoute = MotDePasseOublieRouteImport.update({
  id: '/mot-de-passe-oublie',
  path: '/mot-de-passe-oublie',
  getParentRoute: () => rootRouteImport,
} as any)
const ReinitialiserMotDePasseRoute = ReinitialiserMotDePasseRouteImport.update({
  id: '/reinitialiser-mot-de-passe',
  path: '/reinitialiser-mot-de-passe',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedBibliothequeRoute =
  AuthenticatedBibliothequeRouteImport.update({
    id: '/bibliotheque',
    path: '/bibliotheque',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCreditsRoute = AuthenticatedCreditsRouteImport.update({
  id: '/credits',
  path: '/credits',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedParametresRoute = AuthenticatedParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTarifsRoute = AuthenticatedTarifsRouteImport.update({
  id: '/tarifs',
  path: '/tarifs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTextesRoute = AuthenticatedTextesRouteImport.update({
  id: '/textes',
  path: '/textes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVeilleRoute = AuthenticatedVeilleRouteImport.update({
  id: '/veille',
  path: '/veille',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVideoRoute = AuthenticatedVideoRouteImport.update({
  id: '/video',
  path: '/video',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVisuelsRoute = AuthenticatedVisuelsRouteImport.update({
  id: '/visuels',
  path: '/visuels',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminCreditsRoute =
  AuthenticatedAdminCreditsRouteImport.update({
    id: '/admin/credits',
    path: '/admin/credits',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEbooksIndexRoute =
  AuthenticatedEbooksIndexRouteImport.update({
    id: '/ebooks/',
    path: '/ebooks/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEbooksIdRoute = AuthenticatedEbooksIdRouteImport.update({
  id: '/ebooks/$id',
  path: '/ebooks/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEbooksNouveauRoute =
  AuthenticatedEbooksNouveauRouteImport.update({
    id: '/ebooks/nouveau',
    path: '/ebooks/nouveau',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicWebhooksProviderRoute =
  ApiPublicWebhooksProviderRouteImport.update({
    id: '/api/public/webhooks/$provider',
    path: '/api/public/webhooks/$provider',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mot-de-passe-oublie': typeof MotDePasseOublieRoute
  '/reinitialiser-mot-de-passe': typeof ReinitialiserMotDePasseRoute
  '/bibliotheque': typeof AuthenticatedBibliothequeRoute
  '/credits': typeof AuthenticatedCreditsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/parametres': typeof AuthenticatedParametresRoute
  '/tarifs': typeof AuthenticatedTarifsRoute
  '/textes': typeof AuthenticatedTextesRoute
  '/veille': typeof AuthenticatedVeilleRoute
  '/video': typeof AuthenticatedVideoRoute
  '/visuels': typeof AuthenticatedVisuelsRoute
  '/admin/credits': typeof AuthenticatedAdminCreditsRoute
  '/ebooks/$id': typeof AuthenticatedEbooksIdRoute
  '/ebooks/nouveau': typeof AuthenticatedEbooksNouveauRoute
  '/ebooks/': typeof AuthenticatedEbooksIndexRoute
  '/api/public/webhooks/$provider': typeof ApiPublicWebhooksProviderRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mot-de-passe-oublie': typeof MotDePasseOublieRoute
  '/reinitialiser-mot-de-passe': typeof ReinitialiserMotDePasseRoute
  '/bibliotheque': typeof AuthenticatedBibliothequeRoute
  '/credits': typeof AuthenticatedCreditsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/parametres': typeof AuthenticatedParametresRoute
  '/tarifs': typeof AuthenticatedTarifsRoute
  '/textes': typeof AuthenticatedTextesRoute
  '/veille': typeof AuthenticatedVeilleRoute
  '/video': typeof AuthenticatedVideoRoute
  '/visuels': typeof AuthenticatedVisuelsRoute
  '/admin/credits': typeof AuthenticatedAdminCreditsRoute
  '/ebooks/$id': typeof AuthenticatedEbooksIdRoute
  '/ebooks/nouveau': typeof AuthenticatedEbooksNouveauRoute
  '/ebooks': typeof AuthenticatedEbooksIndexRoute
  '/api/public/webhooks/$provider': typeof ApiPublicWebhooksProviderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/mot-de-passe-oublie': typeof MotDePasseOublieRoute
  '/reinitialiser-mot-de-passe': typeof ReinitialiserMotDePasseRoute
  '/_authenticated/bibliotheque': typeof AuthenticatedBibliothequeRoute
  '/_authenticated/credits': typeof AuthenticatedCreditsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/parametres': typeof AuthenticatedParametresRoute
  '/_authenticated/tarifs': typeof AuthenticatedTarifsRoute
  '/_authenticated/textes': typeof AuthenticatedTextesRoute
  '/_authenticated/veille': typeof AuthenticatedVeilleRoute
  '/_authenticated/video': typeof AuthenticatedVideoRoute
  '/_authenticated/visuels': typeof AuthenticatedVisuelsRoute
  '/_authenticated/admin/credits': typeof AuthenticatedAdminCreditsRoute
  '/_authenticated/ebooks/$id': typeof AuthenticatedEbooksIdRoute
  '/_authenticated/ebooks/nouveau': typeof AuthenticatedEbooksNouveauRoute
  '/_authenticated/ebooks/': typeof AuthenticatedEbooksIndexRoute
  '/api/public/webhooks/$provider': typeof ApiPublicWebhooksProviderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/mot-de-passe-oublie'
    | '/reinitialiser-mot-de-passe'
    | '/bibliotheque'
    | '/credits'
    | '/dashboard'
    | '/parametres'
    | '/tarifs'
    | '/textes'
    | '/veille'
    | '/video'
    | '/visuels'
    | '/admin/credits'
    | '/ebooks/$id'
    | '/ebooks/nouveau'
    | '/ebooks/'
    | '/api/public/webhooks/$provider'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/mot-de-passe-oublie'
    | '/reinitialiser-mot-de-passe'
    | '/bibliotheque'
    | '/credits'
    | '/dashboard'
    | '/parametres'
    | '/tarifs'
    | '/textes'
    | '/veille'
    | '/video'
    | '/visuels'
    | '/admin/credits'
    | '/ebooks/$id'
    | '/ebooks/nouveau'
    | '/ebooks'
    | '/api/public/webhooks/$provider'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/mot-de-passe-oublie'
    | '/reinitialiser-mot-de-passe'
    | '/_authenticated/bibliotheque'
    | '/_authenticated/credits'
    | '/_authenticated/dashboard'
    | '/_authenticated/parametres'
    | '/_authenticated/tarifs'
    | '/_authenticated/textes'
    | '/_authenticated/veille'
    | '/_authenticated/video'
    | '/_authenticated/visuels'
    | '/_authenticated/admin/credits'
    | '/_authenticated/ebooks/$id'
    | '/_authenticated/ebooks/nouveau'
    | '/_authenticated/ebooks/'
    | '/api/public/webhooks/$provider'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  MotDePasseOublieRoute: typeof MotDePasseOublieRoute
  ReinitialiserMotDePasseRoute: typeof ReinitialiserMotDePasseRoute
  ApiPublicWebhooksProviderRoute: typeof ApiPublicWebhooksProviderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mot-de-passe-oublie': {
      id: '/mot-de-passe-oublie'
      path: '/mot-de-passe-oublie'
      fullPath: '/mot-de-passe-oublie'
      preLoaderRoute: typeof MotDePasseOublieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reinitialiser-mot-de-passe': {
      id: '/reinitialiser-mot-de-passe'
      path: '/reinitialiser-mot-de-passe'
      fullPath: '/reinitialiser-mot-de-passe'
      preLoaderRoute: typeof ReinitialiserMotDePasseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/bibliotheque': {
      id: '/_authenticated/bibliotheque'
      path: '/bibliotheque'
      fullPath: '/bibliotheque'
      preLoaderRoute: typeof AuthenticatedBibliothequeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/credits': {
      id: '/_authenticated/credits'
      path: '/credits'
      fullPath: '/credits'
      preLoaderRoute: typeof AuthenticatedCreditsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/parametres': {
      id: '/_authenticated/parametres'
      path: '/parametres'
      fullPath: '/parametres'
      preLoaderRoute: typeof AuthenticatedParametresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tarifs': {
      id: '/_authenticated/tarifs'
      path: '/tarifs'
      fullPath: '/tarifs'
      preLoaderRoute: typeof AuthenticatedTarifsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/textes': {
      id: '/_authenticated/textes'
      path: '/textes'
      fullPath: '/textes'
      preLoaderRoute: typeof AuthenticatedTextesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/veille': {
      id: '/_authenticated/veille'
      path: '/veille'
      fullPath: '/veille'
      preLoaderRoute: typeof AuthenticatedVeilleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/video': {
      id: '/_authenticated/video'
      path: '/video'
      fullPath: '/video'
      preLoaderRoute: typeof AuthenticatedVideoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/visuels': {
      id: '/_authenticated/visuels'
      path: '/visuels'
      fullPath: '/visuels'
      preLoaderRoute: typeof AuthenticatedVisuelsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/credits': {
      id: '/_authenticated/admin/credits'
      path: '/admin/credits'
      fullPath: '/admin/credits'
      preLoaderRoute: typeof AuthenticatedAdminCreditsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ebooks/': {
      id: '/_authenticated/ebooks/'
      path: '/ebooks'
      fullPath: '/ebooks/'
      preLoaderRoute: typeof AuthenticatedEbooksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ebooks/$id': {
      id: '/_authenticated/ebooks/$id'
      path: '/ebooks/$id'
      fullPath: '/ebooks/$id'
      preLoaderRoute: typeof AuthenticatedEbooksIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ebooks/nouveau': {
      id: '/_authenticated/ebooks/nouveau'
      path: '/ebooks/nouveau'
      fullPath: '/ebooks/nouveau'
      preLoaderRoute: typeof AuthenticatedEbooksNouveauRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/webhooks/$provider': {
      id: '/api/public/webhooks/$provider'
      path: '/api/public/webhooks/$provider'
      fullPath: '/api/public/webhooks/$provider'
      preLoaderRoute: typeof ApiPublicWebhooksProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBibliothequeRoute: typeof AuthenticatedBibliothequeRoute
  AuthenticatedCreditsRoute: typeof AuthenticatedCreditsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedParametresRoute: typeof AuthenticatedParametresRoute
  AuthenticatedTarifsRoute: typeof AuthenticatedTarifsRoute
  AuthenticatedTextesRoute: typeof AuthenticatedTextesRoute
  AuthenticatedVeilleRoute: typeof AuthenticatedVeilleRoute
  AuthenticatedVideoRoute: typeof AuthenticatedVideoRoute
  AuthenticatedVisuelsRoute: typeof AuthenticatedVisuelsRoute
  AuthenticatedAdminCreditsRoute: typeof AuthenticatedAdminCreditsRoute
  AuthenticatedEbooksIdRoute: typeof AuthenticatedEbooksIdRoute
  AuthenticatedEbooksNouveauRoute: typeof AuthenticatedEbooksNouveauRoute
  AuthenticatedEbooksIndexRoute: typeof AuthenticatedEbooksIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBibliothequeRoute: AuthenticatedBibliothequeRoute,
  AuthenticatedCreditsRoute: AuthenticatedCreditsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedParametresRoute: AuthenticatedParametresRoute,
  AuthenticatedTarifsRoute: AuthenticatedTarifsRoute,
  AuthenticatedTextesRoute: AuthenticatedTextesRoute,
  AuthenticatedVeilleRoute: AuthenticatedVeilleRoute,
  AuthenticatedVideoRoute: AuthenticatedVideoRoute,
  AuthenticatedVisuelsRoute: AuthenticatedVisuelsRoute,
  AuthenticatedAdminCreditsRoute: AuthenticatedAdminCreditsRoute,
  AuthenticatedEbooksIdRoute: AuthenticatedEbooksIdRoute,
  AuthenticatedEbooksNouveauRoute: AuthenticatedEbooksNouveauRoute,
  AuthenticatedEbooksIndexRoute: AuthenticatedEbooksIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  MotDePasseOublieRoute: MotDePasseOublieRoute,
  ReinitialiserMotDePasseRoute: ReinitialiserMotDePasseRoute,
  ApiPublicWebhooksProviderRoute: ApiPublicWebhooksProviderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
